### ISSUE TITLE
Map Nullable property using convention

### ISSUE THREAD

**Issue by jrshu** [henkmollema/Dapper-FluentMap#82]
When I use the `Convention.Properties<T>` method to define a convention for a nullable type, it strips the nullable part and uses the underlying type instead:
```
var underlyingType = Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T);
```
This causes the properties of any nullable types not to be properly mapped. Is there any reason why you don't want to use the nullable type directly? And is there an alternative preferred way to map nullable properties?

Thanks!

**Comment by henkmollema** [comment]
This is a bug. I meant to normalize the property types to non-nullables so that when you define a convention for `int` properties it is also applied to `int?` properties. However, I did not resolve the underlying type for the property types themself which causes this mismatch. 

I'll change the behavior to the following:
- When defining a convention for `int` (e.g. `Properties<int>`) it will be applied to properties of type `int` as well as type `int?`.
- When explicitly defining a convention for a nullable type (e.g. `Properties<int?>`) it will only be applied to properties of type `int?` and not to the non-nullable type `int`.
